YunoHost-Apps/dont-code_ynh

scripts/_common.sh, scripts/install, scripts/upgrade, scripts/ynh_mongo_db__2
- Mongo installation in CI server is broken
- Check the version of debian 
=> Support other debian versions

scripts/install
=> Trying to understand why Mongo crashes in CI

scripts/ynh_mongo_db__2
=> Trying to install buster version of Mongo

scripts/ynh_mongo_db__2
=> Increased timeout for 15mn

scripts/ynh_mongo_db__2
=> get the systemd log

check_process, scripts/remove, scripts/ynh_mongo_db__2
=> Mongo test

scripts/ynh_mongo_db__2
=> Try to run mongo during install

scripts/ynh_mongo_db__2
=> Why error ?

scripts/ynh_mongo_db__2
=> Why error mongo

scripts/install, scripts/ynh_mongo_db__2
=> Seems like mongod is corrupted

README.md, README_fr.md, manifest.json, scripts/backup, scripts/install, scripts/remove, scripts/restore, scripts/upgrade, scripts/ynh_install_java
=> New version of Java helpers and fix for sudoers backup

README.md, README_fr.md, scripts/ynh_install_java, scripts/ynh_mongo_db__2
=> Trying Mongodb 4.4 for CI & Java certificates

manifest.json, scripts/_common.sh, scripts/ynh_install_java, scripts/ynh_mongo_db__2
=> Trying alternative mongo 4.4 install

scripts/ynh_mongo_db__2
=> Back to installing Mongo 6.0

README.md, README_fr.md, manifest.toml, scripts/upgrade, tests.toml
=> Fixed doc dir issue when upgrading

README.md, README_fr.md, manifest.toml, scripts/upgrade, tests.toml
=> Ensure only needed files are left after upgrade

README.md, README_eu.md, README_fr.md, README_gl.md, conf/nginx.conf, conf/repository-next.json, conf/repository-stable.json, manifest.toml, scripts/change_url, scripts/install, scripts/upgrade
=> Support for auto-repositories

README.md, README_eu.md, README_fr.md, README_gl.md, conf/nginx.conf, conf/repository-next.json, conf/repository-stable.json, manifest.toml, scripts/change_url, scripts/install, scripts/upgrade
=> Support for auto repositories

ALL_README.md, README.md, README_eu.md, README_fr.md, README_gl.md, README_zh_Hans.md, conf/.env, conf/repository-next.json, conf/repository-stable.json, manifest.toml, scripts/ynh_mongo_db__2
=> Cors support fix & Mongo install cleanup

conf/nginx.conf
=> nginx cors headers changed

README.md, README_eu.md, README_fr.md, README_gl.md, README_zh_Hans.md, conf/repository-next.json, conf/repository-stable.json, manifest.toml
=> Changed plugins url in repo files

ALL_README.md, README.md, README_es.md, README_eu.md, README_fr.md, README_gl.md, README_zh_Hans.md, manifest.toml
=> Upgrade to 0.3.2 to fix File upload bug

README.md, README_es.md, README_eu.md, README_fr.md, README_gl.md, README_zh_Hans.md, conf/nginx.conf, manifest.toml, scripts/ynh_mongo_db__2
=> Fixed cors headers for data

README.md, README_es.md, README_eu.md, README_fr.md, README_gl.md, README_zh_Hans.md, manifest.toml
=> fix linter

scripts/install, scripts/restore
=> No need to create log directory anymore

manifest.toml
=> Version update for logs

manifest.toml, scripts/restore
=> restore recreate log dir

.gitignore, ALL_README.md, README_es.md, README_id.md, README_nl.md, README_ru.md, manifest.toml, scripts/_common.sh, scripts/backup, scripts/change_url, scripts/install, scripts/remove, scripts/restore, scripts/upgrade
=> Helpers 2.1

scripts/_mongo_helper.sh
=> Remove avx test

README.md, README_es.md, README_eu.md, README_fr.md, README_gl.md, README_id.md, README_nl.md, README_ru.md, README_zh_Hans.md, manifest.toml, scripts/_common.sh, scripts/_mongo_helper.sh, scripts/backup, scripts/change_url, scripts/install, scripts/restore, scripts/upgrade
=> Bookworm support

manifest.toml, scripts/_mongo_helper.sh
=> Mongo install called unavailable helper

manifest.toml
- Upgrading Dont-code services to a bug fix version
=> Bugfix version 0.3.3
